archive_mode = on
archive_timeout = 1min

archive_command = 'rsync -a --chmod=F600 -e "ssh -i /var/lib/postgresql/.ssh/id_ed25519" %p walarch@192.168.50.40:/srv/postgres/wal/primary/%f.tmp && ssh -i /var/lib/postgresql/.ssh/id_ed25519 walarch@192.168.50.40 mv /srv/postgres/wal/primary/%f.tmp /srv/postgres/wal/primary/%f'