{
 "title": "TimescaleDB Metrics Dashboard",
 "time": { "from": "2026-03-06T16:03:25.126Z", "to": "2026-03-06T16:34:38.447Z" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "metrics",
     "rawSql": "SELECT\r\n  bucket AS time,\r\n  host AS metric,\r\n  avg_value AS value\r\nFROM system_metrics_5m\r\nWHERE metric_name = 'memory_usage'\r\nAND $__timeFilter(bucket)\r\nORDER BY bucket;"
    }
   ]
  },
  {
   "title": "Average CPU by Host",
   "type": "barchart",
   "description": "This calculates average CPU usage per host.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "metrics",
     "rawSql": "SELECT\r\n  host,\r\n  AVG(metric_value) AS avg_cpu\r\nFROM system_metrics\r\nWHERE metric_name = 'cpu_usage'\r\nGROUP BY host\r\nORDER BY avg_cpu DESC;"
    }
   ]
  },
  {
   "title": "CPU Usage Trend",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "metrics",
     "rawSql": "SELECT *\r\nFROM system_metrics\r\nORDER BY time DESC\r\nLIMIT 50;"
    }
   ]
  },
  {
   "title": "Latest CPU Value Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "dataset": "metrics",
     "rawSql": "SELECT\r\nhost,\r\nmetric_value\r\nFROM system_metrics\r\nWHERE metric_name='cpu_usage'\r\nORDER BY time DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "CPU Usage by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "dataset": "metrics",
     "rawSql": "SELECT\r\n  bucket AS time,\r\n  host AS metric,\r\n  avg_value AS value\r\nFROM system_metrics_5m\r\nWHERE metric_name = 'cpu_usage'\r\nAND $__timeFilter(bucket)\r\nORDER BY time;"
    }
   ]
  }
 ]
}