{
 "title": "TimescaleDB",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "SELECT DISTINCT hostname FROM logs.platform_logs ORDER BY hostname"
   }
  ]
 },
 "panels": [
  {
   "title": "Services Generating Most Logs",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  service,\r\n  count() AS rows\r\nFROM logs.platform_logs\r\nWHERE hostname IN (${hostname:sqlstring})\r\nAND timestamp >= now() - INTERVAL 1 HOUR\r\nGROUP BY service\r\nORDER BY rows DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Logs over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfMinute(timestamp) AS time,\r\n  count() AS logs_count\r\nFROM logs.platform_logs\r\nWHERE hostname IN (${hostname:sqlstring})\r\nAND timestamp >= now() - INTERVAL 1 HOUR\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Error Rate by Service",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    service,\r\n    count() AS errors\r\nFROM logs.platform_logs\r\nWHERE hostname IN (${hostname:sqlstring})\r\nAND toInt32(level) <= 6\r\nAND timestamp >= now() - INTERVAL 1 HOUR\r\nGROUP BY service\r\nORDER BY errors DESC"
    }
   ]
  },
  {
   "title": "Severity Distribution Panel",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    level,\r\n    count() AS logs\r\nFROM logs.platform_logs\r\nWHERE hostname IN (${hostname:sqlstring})\r\nAND timestamp >= now() - INTERVAL 1 HOUR\r\nGROUP BY level\r\nORDER BY level"
    }
   ]
  },
  {
   "title": "Live Log Stream",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp,\r\n  hostname,\r\n  service,\r\n  level,\r\n  source_type,\r\n  message\r\nFROM logs.platform_logs\r\nORDER BY timestamp DESC\r\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Top error messages",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  message,\r\n  count() AS occurrences\r\nFROM logs.platform_logs\r\nWHERE hostname IN (${hostname:sqlstring})\r\nAND toInt32(level) <= 6\r\nAND timestamp >= now() - INTERVAL 1 HOUR\r\nGROUP BY message\r\nORDER BY occurrences DESC\r\nLIMIT 10"
    }
   ]
  }
 ]
}