global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts/*.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"

  # File-based discovery (recommended)
  - job_name: "nodes"
    file_sd_configs:
      - files:
          - "targets/*.yml"

  # Optional: direct static scrape example
  - job_name: "ai-gpu-node"
    static_configs:
      - targets: ["IP:9400"]