global: {}

route:
  receiver: "default"
  group_by: ["alertname", "job", "instance"]
  group_wait: 10s
  group_interval: 2m
  repeat_interval: 4h

receivers:
  - name: "default"
    # Start with local testing (no external notifications).
    # Later add email/telegram/discord/webhook here.