[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info

[INPUT]
    Name              systemd
    Tag               host.*
    Read_From_Tail    On

[FILTER]
    Name              lua
    Match             host.*
    script            /etc/fluent-bit/transform.lua
    call              build_record

[OUTPUT]
    Name              http
    Match             host.*
    Host              HOST-IP
    Port              8123
    URI               /?query=INSERT%20INTO%20logs.platform_logs%20FORMAT%20JSONEachRow
    Format            json_lines